from django.contrib.auth.views import PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView, \
    PasswordResetDoneView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, reverse_lazy
from .views import *

urlpatterns = [
    path('user/create/', create_user, name='create-user'),
    # path('users_list/', user_list, name='user-list'),
    # path('users_listview/', user_listview, name='user-listview'),
    path('main_dashboard/', main_dashboard, name='main_dashboard'),
    path('create_profile/', create_profile, name='create_profile'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('get_country_states/', get_country_states, name='get_country_states'),
    path('get_countries/', get_countries, name='get_countries'),
    path('verification/', verification, name='verification'),
    path('global_config/', global_config, name='global_config'),
    path('billing_charge_per_minute/', billing_charge_per_minute, name='billing_charge_per_minute'),
    path('create_global_setting/', create_global_setting, name='create_global_setting'),
    path('password-reset/', PasswordResetView.as_view(template_name='user_management/Reset_Password/reset_password.html',
         html_email_template_name='user_management/Reset_Password/password_reset_html_email.html',
         email_template_name='user_management/Reset_Password/reset_password_email.html',), name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name='user_management/Reset_Password/reset_password_done.html',),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='user_management/Reset_Password/reset_password_confirm.html',),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='user_management/Reset_Password/reset_password_complete.html',),
         name='password_reset_complete'),
    # path('password_change/',
    #      PasswordChangeView.as_view(template_name='user_management/profile_password_change_form.html',
    #                                 success_url=reverse_lazy('main_dashboard'),),
    #      name='password_change'),
    # path('password_change/done/',
    #      PasswordChangeDoneView.as_view(template_name='user_management/password_change_done.html',),
    #      name='password_change_done'),
    path('get_global_settings/', get_global_settings, name='get_global_settings'),
    path('edit_global_settings/', edit_global_settings, name='edit_global_settings'),
    path('settings/', settings, name='settings'),
    path('edit_user_profile/', edit_user_profile, name='edit_user_profile'),
    path('get_user_details/', get_user_details, name='get_user_details'),
    path('terms_conditions/', terms_conditions, name='terms_conditions'),
    path('privacy_policy/', privacy_policy, name='privacy_policy'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
]
