# Generated by Django 3.2 on 2021-06-09 10:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0002_auto_20210609_1038'),
        ('sessions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_access', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'global_setting',
            },
        ),
        migrations.CreateModel(
            name='SessionCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('i_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
            ],
            options={
                'db_table': 'session_credentials',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='i_user', serialize=False, to='auth.user')),
                ('qr_verified', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('end_trial_date', models.DateTimeField(blank=True, null=True)),
                ('is_trial_active', models.BooleanField(default=False)),
                ('profile_completion_status', models.BooleanField(default=False)),
                ('i_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
                ('permission_groups', models.ManyToManyField(blank=True, related_name='i_permission_groups', to='permissions.PermissionGroups')),
                ('permission_tags', models.ManyToManyField(blank=True, related_name='i_permission_tags', to='permissions.PermissionTags')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ClientVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.PositiveIntegerField()),
                ('email_sent', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField(editable=False)),
                ('i_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'db_table': 'client_verification',
            },
        ),
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_os', models.CharField(max_length=256)),
                ('hardware', models.CharField(max_length=256)),
                ('country', models.CharField(default='default', max_length=256)),
                ('user_ip', models.CharField(default='user_ip', max_length=256)),
                ('system_hardware', models.CharField(default='default', max_length=256)),
                ('i_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'db_table': 'client_details',
            },
        ),
    ]
