# Generated by Django 3.2 on 2021-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210615_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsetting',
            name='allow_access',
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='name',
            field=models.CharField(default='billing_charge_per_second', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='value',
            field=models.CharField(default='0.5', max_length=32),
            preserve_default=False,
        ),
    ]
