# Generated by Django 3.2 on 2021-06-10 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import itrans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('length', models.CharField(max_length=128)),
                ('uploaded_on', models.DateTimeField(default=datetime.datetime.now)),
                ('file_path', models.FileField(max_length=256, upload_to=itrans.models.get_file_path)),
                ('transcribed_file', models.FileField(blank=True, max_length=256, null=True, upload_to=itrans.models.get_transcribed_file)),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_info',
            },
        ),
    ]
