# Generated by Django 3.2 on 2021-06-11 07:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='transcribed_file_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='length',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
