# Generated by Django 3.2 on 2021-06-15 07:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itrans', '0003_alter_fileinfo_transcribed_file_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'stripe_type',
            },
        ),
        migrations.CreateModel(
            name='StripeAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ref_id', models.CharField(max_length=256)),
                ('i_stripe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itrans.stripetype')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_stripe_mapping',
            },
        ),
        migrations.CreateModel(
            name='FileJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('job_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('i_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itrans.fileinfo')),
            ],
            options={
                'db_table': 'file_job',
            },
        ),
    ]
