# Generated by Django 3.2 on 2021-06-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0005_alter_stripeaccountmapping_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method_ref_id', models.CharField(max_length=256)),
                ('payment_method_meta', models.JSONField()),
                ('i_stripe_acc_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itrans.stripeaccountmapping')),
            ],
            options={
                'db_table': 'payment_method_mapping',
            },
        ),
    ]
