# Generated by Django 3.2 on 2021-06-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0007_auto_20210618_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='transcribed_file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
