# Generated by Django 3.2 on 2021-06-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0008_fileinfo_transcribed_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filejob',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filejob',
            name='job_status',
            field=models.CharField(choices=[('on hold', 'On Hold'), ('processing', 'Processing'), ('completed', 'Completed')], default='on hold', max_length=32),
        ),
    ]
