# Generated by Django 3.2 on 2021-07-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0009_auto_20210630_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='filejob',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
