# Generated by Django 3.2 on 2021-08-30 06:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import itrans.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itrans', '0010_filejob_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('shortcode', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('watermark', models.ImageField(blank=True, max_length=256, null=True, upload_to=itrans.models.get_watermarks_path)),
                ('logo', models.ImageField(blank=True, max_length=256, null=True, upload_to=itrans.models.get_logo_path)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.RemoveField(
            model_name='fileinfo',
            name='i_user',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('total_length', models.CharField(blank=True, max_length=128, null=True)),
                ('total_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('service_type', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamping', models.CharField(blank=True, max_length=128, null=True)),
                ('verbatim', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='i_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itrans.project'),
        ),
    ]
