# Generated by Django 3.2 on 2021-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0012_auto_20210830_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
