# Generated by Django 3.2 on 2021-09-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0013_project_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='instant_first_draft',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rush_my_order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='timestamping',
        ),
        migrations.RemoveField(
            model_name='project',
            name='verbatim',
        ),
    ]
