# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-08 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RbacPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('add_permission', models.CharField(blank=True, max_length=256, null=True)),
                ('view_permission', models.CharField(blank=True, max_length=256, null=True)),
                ('detail_permission', models.CharField(blank=True, max_length=256, null=True)),
                ('delete_permission', models.CharField(blank=True, max_length=256, null=True)),
                ('change_permission', models.CharField(blank=True, max_length=256, null=True)),
                ('import_permission', models.CharField(blank=True, max_length=256, null=True)),
                ('export_permission', models.CharField(blank=True, max_length=256, null=True)),
                ('other_permission', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'rbac_preference',
            },
        ),
        migrations.CreateModel(
            name='RbacPreferenceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('group', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'rbac_preference_group',
            },
        ),
        migrations.AddField(
            model_name='rbacpreference',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac_preferences.RbacPreferenceGroup'),
        ),
    ]
