# Generated by Django 3.2 on 2021-06-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbacpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rbacpreferencegroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
