# Generated by Django 3.2 on 2021-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, verbose_name='Email *')),
                ('password', models.CharField(max_length=128, verbose_name='Password *')),
                ('confirm_password', models.CharField(max_length=128, verbose_name='Confirm Password *')),
                ('host', models.CharField(max_length=128, verbose_name='Host *')),
                ('category', models.CharField(choices=[('warning', 'Warning'), ('alerts', 'Alerts'), ('verification_code', 'Verification Code')], max_length=30, unique=True, verbose_name='Category *')),
                ('port', models.CharField(choices=[('587', '587'), ('465', '465'), ('25', '25')], default='465', max_length=8, verbose_name='Port *')),
                ('port_type', models.CharField(choices=[('SSL', 'TLS/SSL'), ('StartTLS', 'STARTTLS'), ('None', 'None')], default='TLS/SSL', max_length=8, verbose_name='Port Type *')),
                ('timeout', models.IntegerField(verbose_name='Timeout(seconds) *')),
            ],
            options={
                'db_table': 'send_email',
            },
        ),
    ]
