# Generated by Django 3.2 on 2021-06-18 06:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'stripe_type',
            },
        ),
        migrations.CreateModel(
            name='StripeAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ref_id', models.CharField(max_length=256)),
                ('i_stripe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_payments.stripetype')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_account_mapping',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_method_ref_id', models.CharField(max_length=256)),
                ('payment_method_meta', models.JSONField()),
                ('i_stripe_acc_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_payments.stripeaccountmapping')),
            ],
            options={
                'db_table': 'payment_method_mapping',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_log', models.TextField()),
                ('remarks', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('i_stripe_acc_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_payments.stripeaccountmapping')),
            ],
            options={
                'db_table': 'payment_method_error_log',
            },
        ),
    ]
