# Generated by Django 3.2 on 2021-06-30 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0009_auto_20210630_0725'),
        ('stripe_payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('ref_id', models.CharField(blank=True, max_length=64, null=True)),
                ('i_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itrans.filejob')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
