# Generated by Django 3.2 on 2021-08-30 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itrans', '0011_auto_20210830_0630'),
        ('stripe_payments', '0002_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='i_job',
        ),
        migrations.AddField(
            model_name='payments',
            name='i_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itrans.project'),
        ),
    ]
