# Generated by Django 3.2 on 2021-09-23 09:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_payments', '0003_auto_20210830_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPaymentErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_log', models.TextField()),
                ('remarks', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('i_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_payment_error_log',
            },
        ),
    ]
