# Generated by Django 3.2 on 2021-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_by', models.CharField(max_length=128)),
                ('action_by_id', models.PositiveIntegerField()),
                ('action_date', models.DateTimeField()),
                ('action_desc', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'system_logs',
            },
        ),
    ]
